#!/bin/bash
set -eu

# Wrapper around kustomize since kapitan expects absolute paths for system binaries.

# Kapitan does not respect the PATH variable from the environment, so we need to add some common paths.
export PATH="${PATH}:/usr/local/bin:/opt/homebrew/bin"

kustomize=$(which kustomize) || (>&2 echo "kustomize not found in ${PATH}"; exit 7)

exec "$kustomize" "$@"
