= Parameters

The parent key for all of the following parameters is `openshift4_slos`.

== `namespace`

[horizontal]
type:: string
default:: `appuio-openshift4-slos`

The default namespace for ArgoCD to fall back to.


== `images`

[horizontal]
type:: dictionary

The images to use for this component.

== `images.sloth`

[horizontal]
type:: dictionary

Sloth isn't actually deployed to the cluster, but used to render `PrometheusRules`.

The entry in `images` allows Renovate to create version upgrade PRs.
The Sloth version can be overridden by the `tag` parameter.

== `alerting`

[horizontal]
type:: dictionary

Common alerting configuration for all deployed SLOs.

=== `alerting.labels`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
labels:
  syn: "true"
  syn_component: "openshift4-slos"
----

Labels that are added to all Prometheus alerts generated by this component.

=== `alerting.page_labels`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
page_labels:
  severity: critical
----

Labels that are added to all `page` Prometheus alerts generated by this component.
`page_alerts` are alerts are critical alerts for a high burn rate that require immediate attention.

=== `alerting.ticket_labels`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
ticket_labels:
  severity: warning
----

Labels that are added to all `ticket` Prometheus alerts generated by this component.
`ticket_alerts` are alerts are alerts for an elevated burn rate that might require attention, but aren't urgent.

== `specs`

[horizontal]
type:: dictionary
default:: `{}`

The SLO definition that are passed to Sloth.
The key is used as the name of the resulting PrometheusRule.
It must be a valid Kubernetes name.


=== `specs.NAME.metadata`

[horizontal]
type:: dictionary
example::
+
[source,yaml]
----
metadata:
  namespace: my-important-service
  labels:
    prometheus: apps
----

The metadata applied to the PrometheusRule manifest.
The name is derived from the name of the parent dictionary.


=== `specs.NAME.sloth_input`

[horizontal]
type:: dictionary
example::

[source,yaml]
----
appuio-ch-http-get-availability:
  sloth_input:
    version: "prometheus/v1"
    service: "appuio-ch"
    labels:
      owner: "myteam"
    _slos:
      # We allow failing (5xx and 429) 1 request every 1000 requests (99.9%).
      appuio-ch-http-get-availability:
        enabled: true <1>
        objective: 99.9
        description: "SLO based on availability for blackbox HTTP GET request."
        sli:
          raw:
            error_ratio_query: |
              1 - (
                  sum_over_time(probe_success{instance="https://www.appuio.ch/"}[{{.window}}])
                /
                  count_over_time(up{instance="https://www.appuio.ch/"}[{{.window}}])
              )
        alerting:
          name: AppuioChHttpGetErrorRatio
          labels:
            category: "availability"
          annotations:
            # Overwrite default Sloth SLO alert summmary on ticket and page alerts.
            summary: "High error rate on 'appuio.ch' responses"
          page_alert:
            labels:
              severity: warning
          ticket_alert:
            labels:
              severity: warning
              routing_key: myteam
----
<1> `enabled` is an optional field that allows users to disable certain SLOs through the hierarchy.
The field will default to `true` if omitted.

The input for sloth to generate the `PrometheusRule.spec`.
See https://sloth.dev/introduction/[Sloth introduction] for more information.

The `slos` can be passed as either an array or as a dictionary with the key `_slos`.
This is done to allow easier modification of the SLOs from the Project Syn hierarchy.


== `blackbox_exporter`

[horizontal]
type:: dictionary

`blackbox_exporter` allows setting up a optional Blackbox exporter.


=== `blackbox_exporter.enabled`

[horizontal]
type:: boolean
default:: `true`

Controls whether the Blackbox exporter is deployed.


=== `blackbox_exporter.name`

[horizontal]
type:: string
default:: `prometheus-blackbox-exporter`

The name of the Blackbox exporter deployment.


=== `blackbox_exporter.namespace`

[horizontal]
type:: string
default:: `${openshift4_slos:namespace}`

The namespace of the Blackbox exporter deployment.


=== `blackbox_exporter.deployment.resources`

[horizontal]
type:: dictionary
default:: see https://github.com/appuio/component-openshift4-slos/blob/master/class/defaults.yml[class/defaults.yml]

The resources to use for the Blackbox exporter deployment.


=== `blackbox_exporter.config`

[horizontal]
type:: dictionary
default:: see https://github.com/appuio/component-openshift4-slos/blob/master/class/defaults.yml[class/defaults.yml]

The blackbox exporter configuration. See https://github.com/prometheus/blackbox_exporter#configuration[Configuration] for more information.


=== `blackbox_exporter.probes`

[horizontal]
type:: dictionary
default:: `{}`
example::
+
[source,yaml]
----
probes:
  http-appuio-ch:
    spec:
      jobName: get-http-appuio-ch
      interval: 15s
      module: http_2xx
      targets:
        staticConfig:
          static:
            - https://www.appuio.ch/
----

The https://docs.openshift.com/container-platform/4.10/rest_api/monitoring_apis/probe-monitoring-coreos-com-v1.html[Probe] definitions that are deployed in the cluster and picked up by the blackbox exporter managed by the component.
The key is used as the name of the resulting Probe.
It must be a valid Kubernetes name.

[INFO]
The `.spec.prober` part is automatically filled from the Blackbox exporter configuration and can omitted.


== Example

[source,yaml]
----
namespace: appuio-openshift4-slos

specs:
  appuio-ch-http-get-availability:
    sloth_input:
      version: "prometheus/v1"
      service: "appuio-ch"
      labels:
        owner: "myteam"
      _slos:
        # We allow failing (5xx and 429) 1 request every 1000 requests (99.9%).
        appuio-ch-http-get-availability:
          objective: 99.9
          description: "SLO based on availability for blackbox HTTP GET request."
          sli:
            raw:
              error_ratio_query: |
                1 - (
                    sum_over_time(probe_success{instance="https://www.appuio.ch/"}[{{.window}}])
                  /
                    count_over_time(up{instance="https://www.appuio.ch/"}[{{.window}}])
                )
          alerting:
            name: AppuioChHttpGetErrorRatio
            labels:
              category: "availability"
            annotations:
              # Overwrite default Sloth SLO alert summmary on ticket and page alerts.
              summary: "High error rate on 'appuio.ch' responses"
            page_alert:
              labels:
                severity: warning
            ticket_alert:
              labels:
                severity: warning
                routing_key: myteam

blackbox_exporter:
  probes:
    http-appuio-ch:
      spec:
        jobName: get-http-appuio-ch
        interval: 15s
        module: http_2xx
        targets:
          staticConfig:
            static:
              - https://www.appuio.ch/
----
